WORLD = {
    "menu": {
        "desc": "Voce esta no menu principal.",
        "exits": {},
        "items": [],
        "scene": "menu",
        "region": "menu",
        "encounters_enabled": False,
    },
    "praia": {
        "desc": "Voce esta em uma praia silenciosa. O mar murmura ao sul. A luz da lua reflete nas ondas do mar a sua frente.",
        "exits": {"norte": "floresta", "leste": "caverna"},
        "items": ["concha"],
        "scene": "praia",
        "region": "praia",
        "encounters_enabled": False,
    },
    "floresta": {
        "desc": "Arvores densas bloqueiam parte da luz noturna. Ha um cheiro de terra molhada.",
        "exits": {"sul": "praia"},
        "items": ["galho"],
        "scene": "floresta",
        "region": "floresta",
        "encounters_enabled": True,
    },
    "caverna": {
        "desc": "Uma caverna escura e fria. Ecoa o som de gotas.",
        "exits": {"oeste": "praia", "entrada": "interior da caverna"},
        "items": ["tocha"],
        "scene": "caverna",
        "region": "caverna",
        "encounters_enabled": True,
    },
    "interior da caverna": {
        "desc": "Voce esta dentro de uma caverna escura. Ha um brilho fraco vindo de uma abertura ao norte.",
        "exits": {"norte": "planicie"},
        "items": [],
        "scene": "interior da caverna",
        "region": "caverna",
        "encounters_enabled": True,
    },
    "planicie": {
        "desc": "Voce chegou a uma planicie aberta com grama rala. O ceu estrelado se estende acima de voce.",
        "exits": {"sul": "interior da caverna", "oeste": "floresta", "norte": "leste da vila"},
        "items": [],
        "scene": "planicie",
        "region": "planicie",
        "encounters_enabled": True,
    },
    "leste da vila": {
        "desc": "Voce chegou ao leste da vila. Casas simples se alinham ao longo da estrada de terra.",
        "exits": {"sul": "planicie", "oeste": "vila"},
        "items": [],
        "scene": "leste da vila",
        "region": "vila",
        "encounters_enabled": True,
    },
}
